[package]
name = "event_parse"
version = "0.1.0"
authors = ["Johan Burell <johan.burell@valtech.se>"]

[dependencies]
libevdev-sys = "0.1.1"
libc = "*"
custom_derive = "*"
newtype_derive = "*"
enum_primitive = "*"
num = "*"
itertools = "0.7.3"